### ISSUE TITLE
Firebase token registration is blank

### ISSUE THREAD

**Issue by scrummitch** [autopilot3/ortto-flutter-sdk#7]
From customer

```bash
W/ortto@sdk(23330): dispatchPushRequest@dispatchPushRequest firebase.getToken.fail
```

This error message is logged when I call the method Ortto.instance.dispatchPushRequest()

Note that firebase method final token = await FirebaseMessaging.instance.getToken(); correctly returns a token, which makes me think that the firebase sdk is properly configured.

Not sure what's wrong here. I don't have much more info to provide here except that this used to work in the past.

The firebase messaging version installed in our app is this one :

```yaml
firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      sha256: a1662cc95d9750a324ad9df349b873360af6f11414902021f130c68ec02267c4
      url: "https://pub.dev/"
    source: hosted
    version: "14.9.4"
```

```dart
await Ortto.instance.init(
      appKey: AppConfig.orttoAppKey,
      endpoint: AppConfig.orttoAppEndpoint,
    );

await Ortto.instance.initCapture(
      dataSourceKey: AppConfig.orttoDatasourceKey,
      captureJsUrl: AppConfig.orttoCaptureJsUrl,
      apiHost: AppConfig.orttoApiHost,
);

await Ortto.instance.identify(UserID(
      externalId: user?.id,
      email: user?.email,
      firstName: user?.infos?.firstName,
      lastName: user?.infos?.lastName,
));

await Ortto.instance.dispatchPushRequest();
```

```yaml
firebase_core:
    dependency: transitive
    description:
      name: firebase_core
      sha256: "26de145bb9688a90962faec6f838247377b0b0d32cc0abecd9a4e43525fc856c"
      url: "https://pub.dev/"
    source: hosted
    version: "2.32.0"
  firebase_core_platform_interface:
    dependency: transitive
    description:
      name: firebase_core_platform_interface
      sha256: e30da58198a6d4b49d5bce4e852f985c32cb10db329ebef9473db2b9f09ce810
      url: "https://pub.dev/"
    source: hosted
    version: "5.3.0"
  firebase_core_web:
    dependency: transitive
    description:
      name: firebase_core_web
      sha256: "362e52457ed2b7b180964769c1e04d1e0ea0259fdf7025fdfedd019d4ae2bd88"
      url: "https://pub.dev/"
    source: hosted
    version: "2.17.5"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      sha256: a1662cc95d9750a324ad9df349b873360af6f11414902021f130c68ec02267c4
      url: "https://pub.dev/"
    source: hosted
    version: "14.9.4"
  firebase_messaging_platform_interface:
    dependency: transitive
    description:
      name: firebase_messaging_platform_interface
      sha256: "87c4a922cb6f811cfb7a889bdbb3622702443c52a0271636cbc90d813ceac147"
      url: "https://pub.dev/"
    source: hosted
    version: "4.5.37"
  firebase_messaging_web:
    dependency: transitive
    description:
      name: firebase_messaging_web
      sha256: "0d34dca01a7b103ed7f20138bffbb28eb0e61a677bf9e78a028a932e2c7322d5"
      url: "https://pub.dev/"
    source: hosted
    version: "3.8.7"
```

> I can confirm firebase is initialized before. (which is confirmed by what I mentionned in my first message when I say that :
Note that firebase method final token = await FirebaseMessaging.instance.getToken(); correctly returns a token, which makes me think that the firebase sdk is properly configured.
Perhaps try calling dispatch after an event like a button click.
=> Yes, that’s already what I’m doing here.
Otherwise, you can pass the token directly to the Ortto SDK
=> Does not seem possible, as it seems to me this method is not implemented on the android part of the flutter sdk :
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method registerDeviceToken on channel ortto_flutter_sdk_android)
I can confirm this method does not exist in the code of the SDK
